name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version to test use semver format e.g. v1.0.0' 
        required: true
        default: 'v1'

jobs:
  test:
    name: Init Repository
    if: github.repository_owner == 'jairandresdiazp'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Setup package manager
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: true

  build:
    name: Build bundle
    if: github.repository_owner == 'jairandresdiazp'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --global user.email "${{ github.actor }}"
          git config --global user.name "${{ github.repository_owner }}"

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Setup package manager
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: true
      - run: |
          pnpm run build

      - name: Git add build
        run: |
          git add .
          git commit -m "Auto commit from Github Actions #${{ github.run_id }}"
          git push origin -f

  deploy:
    name: Deploy Bundle
    if: github.repository_owner == 'jairandresdiazp'
    runs-on: ubuntu-latest
    needs:
      - test
      - build

    steps:
      - name: Set Time
        run: echo "TIME=$(date --rfc-3339=date)" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_REPO_ACCESS_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          commitish: main
          body: |
            Created on ${{ env.TIME }} using automated Workflow by ${{ github.actor }}
          draft: false
          prerelease: false